---
title: "ggPMX stratification"
author: "Vignette Author"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
\clearpage  
```{r load_package, echo=FALSE,warning=FALSE,message=FALSE}

params. <- 
  list(case = "1_popPK_model", 
       wd = "/home/agstudy/SVN/ggPMX_doc/USER_EXAMPLES/MLX//PK_WITH_COVARIATE_IOV/1_popPK_model", 
       type = "PK", 
       input = "PKdata_ggPMX.csv", 
       dv = "DV", 
       dvid = "ytype", 
       occ = "ISS",
       cats = "SEX;RACE;DISE;ILOW", 
       conts = "AGE0;WT0;HT0;TRT")

with(params.,
     pmxOptions(
       work_dir=file.path(wd,"RESULTS"),
       input=file.path(wd,input),
       dv=dv,
       dvid=dvid,
       cats=unlist(strsplit(cats,";")),
       conts=unlist(strsplit(conts,";")),
       occ=occ
     )
)

settings <-  
  list(
    draft=FALSE, 
    strats = "SEX")

```

```{r}
ctr <- pmx_mlx("standing", settings=settings)
## faceting stratification 
ctr %>% set_plot("RES","p1",x="IPRED",y="IWRES",strat.facet=SEX+ILOW~RACE+DISE)
## color stratification 
ctr %>% set_plot("RES","p2",x="IPRED",y="IWRES",strat.color="AGE0")
## color+facet stratification 
ctr %>% set_plot("RES","p3",x="IPRED",y="IWRES",strat.color="SEX",strat.facet=SEX~RACE)

## color+facet stratification 
ctr %>% set_plot("DIS","p4", strat.facet=~SEX)
## color+facet stratification 
ctr %>% set_plot("DIS","p5", strat.facet=DISE~RACE,strat.color="SEX",
                 has.jitter=FALSE)
## color+facet stratification 
ctr %>% set_plot("DIS","p6", strat.facet="SEX",type="hist")
## color+facet stratification 
ctr %>% set_plot("IND","p7", strat.facet=~SEX)
ctr %>% get_plot("p1")
ctr %>% get_plot("p2")
ctr %>% get_plot("p3")
ctr %>% get_plot("p4")
ctr %>% get_plot("p5")
ctr %>% get_plot("p6")
ctr %>% get_plot("p7",1)



```

