#' Creates parameter table
#'
#' @param ctr The controller generated by pmx/pmx_mlx/pmx_mlxtran/pmx_nlmixr/pmx_nm
#' @param print_tibble If TRUE, returns tibble if FALSE returns kable
#'
#' @return Returns an improved tibble or a kable with the parameter estimates from ctr %>% get_data('estimates')
#' @export
#'
#' @examples
#' #ctr <- theophylline()
#' #my_params <- ctr %>% param_table()

param_table <- function(ctr,fun,return_table = FALSE) {
  #browser()
  
  if(missing(fun)) stop("fun needs to be specified as sd or var, see ?param_table for more information")
  
  pop_pars = ctr %>% get_data('estimates')
  
  if(ctr$config$sys == "mlx"){
    
    shrinkage = ctr %>% pmx_comp_shrink(fun=fun) %>% 
      dplyr::mutate(SHRINK=paste0(round(SHRINK*100),'%')) %>% # make % shrinkage
      dplyr::mutate(PARAM=paste0('omega_',EFFECT)) %>%  #generate new column PARAM with "omega_" prefix
      dplyr::select(PARAM,SHRINK) %>% #select PARAM and SHRINK (%)
      dplyr::mutate(PARAM = as.character(PARAM))
    
    pop_pars2 = pop_pars %>% 
      dplyr::mutate(VALUE=as.character(signif(VALUE,2)),RSE=ifelse(is.na(RSE), 'fixed',paste0(round(RSE),'%'))) %>% #make RSE in %, and NaN to "fixed"
      dplyr::select(PARAM,VALUE,RSE) %>% #select param and value
      dplyr::mutate(PARAM = as.character(PARAM)) %>% #set param as character
      dplyr::arrange(PARAM) %>% #sort according to param
      dplyr::mutate(PARAM = trimws(PARAM)) %>% #remove white space
      dplyr::left_join(shrinkage, by = "PARAM") %>% #join shrinkage
      dplyr::mutate(SHRINK=ifelse(is.na(SHRINK),'',SHRINK)) # remove NAs from empty shrink
    
    pop_pars3 =  dplyr::bind_rows(pop_pars2 %>% filter(grepl('_pop',PARAM))) %>% 
      dplyr::bind_rows(data.frame(PARAM=' ',VALUE='', RSE ='', SHRINK='')) %>%
      dplyr::bind_rows(pop_pars2 %>% filter(grepl('omega_',PARAM))) %>% 
      dplyr::bind_rows(data.frame(PARAM=' ',VALUE='', RSE ='', SHRINK='')) %>%
      dplyr::bind_rows(pop_pars2 %>% filter(grepl('beta_',PARAM))) %>% 
      dplyr::bind_rows(data.frame(PARAM=' ',VALUE='',RSE ='', SHRINK='')) %>%
      dplyr::bind_rows(pop_pars2 %>% filter(PARAM %in% c('a','b'))) %>% 
      dplyr::rename(Parameter=PARAM, Estimate=VALUE, Relative_SE=RSE,Shrinkage=SHRINK)
  }

  if(ctr$config$sys == "nm"){ #will not merge according shrink, because different names, and shrink calculated with SD, but should be variance (but this should be ok)
    
    browser()
    
    shrinkage = ctr %>% pmx_comp_shrink(fun = fun) %>% #because for nonmem data is used of get_data("omega"), which is the SD
      dplyr::mutate(SHRINK=paste0(round(SHRINK*100),'%')) %>% # make % shrinkage
      dplyr::mutate(PARAM=EFFECT) %>%  #generate new column PARAM with "omega_" prefix
      dplyr::select(PARAM,SHRINK) %>% #select PARAM and SHRINK (%)
      dplyr::mutate(PARAM = as.character(PARAM))
    
    i = 1
    for(i in i:length(shrinkage$PARAM)) {
      str <- shrinkage$PARAM[i]
      num <- as.numeric(substring(str,4,))
      shrinkage$PARAM[i] <- paste0("OMEGA(",num,",",num,")")
    }
    
    pop_pars2 = pop_pars %>% 
      dplyr::mutate(VALUE=as.character(signif(VALUE,2))) %>% #make RSE in %, and NaN to "fixed" #RSE=ifelse(is.na(RSE), 'fixed',paste0(round(RSE),'%'))
      dplyr::select(PARAM,VALUE,RSE) %>% #select param and value
      dplyr::mutate(PARAM = as.character(PARAM)) %>% #set param as character
      dplyr::arrange(PARAM) %>% #sort according to param
      dplyr::mutate(PARAM = trimws(PARAM)) %>% #remove white space
      dplyr::left_join(shrinkage, by = "PARAM") %>% #join shrinkage
      dplyr::mutate(SHRINK=ifelse(is.na(SHRINK),'',SHRINK)) # remove NAs from empty shrink
    
    pop_pars3 =  dplyr::bind_rows(pop_pars2 %>% filter(grepl('OBJ',PARAM))) %>% 
      dplyr::bind_rows(data.frame(PARAM=' ',VALUE='', RSE ='', SHRINK='')) %>%
      dplyr::bind_rows(pop_pars2 %>% filter(grepl('THETA',PARAM))) %>% 
      dplyr::bind_rows(data.frame(PARAM=' ',VALUE='', RSE ='', SHRINK='')) %>%
      dplyr::bind_rows(pop_pars2 %>% filter(grepl('SIGMA',PARAM))) %>% 
      dplyr::bind_rows(data.frame(PARAM=' ',VALUE='', RSE ='', SHRINK='')) %>%
      dplyr::bind_rows(pop_pars2 %>% filter(grepl('OMEGA',PARAM))) %>% 
      dplyr::bind_rows(data.frame(PARAM=' ',VALUE='',RSE ='', SHRINK='')) %>%
      dplyr::bind_rows(pop_pars2 %>% filter(PARAM %in% c('a','b'))) %>% 
      dplyr::rename(Parameter=PARAM, Estimate=VALUE, Relative_SE=RSE,Shrinkage=SHRINK)
    
    #browser()
  }
  
  if(ctr$config$sys == "nlmixr"){
    message("param_table is not yet implemented for nlmixr")
  }
  
  if(return_table) {
    pop_pars3 <- as_tibble(pop_pars3)
    return_kable <- FALSE
  } else {
    return_kable <- TRUE
  }
  
  if(return_kable) {
    pop_pars3 <- pop_pars3 %>% knitr::kable(col.names = c("Parameter", "Value", "Relative Standard Error","Shrinkage"), caption=paste0('Parameter estimates (',nrow(pop_pars3)+1,' lines)'))
  }
  
  return(pop_pars3)
  
}


