name: R-hub
run-name: "${{ github.event.inputs.id }}: ${{ github.event.inputs.name || format('Manually run by {0}', github.triggering_actor) }}"

on:
  workflow_dispatch:
    inputs:
      config:
        description: 'A comma separated list of R-hub platforms to use.'
        type: string
        default: 'linux,windows,macos'
      name:
        description: 'Run name. You can leave this empty now.'
        type: string
      id:
        description: 'Unique ID. You can leave this empty now.'
        type: string

jobs:

  setup:
    runs-on: ubuntu-latest
    outputs:
      containers: ${{ steps.rhub-setup.outputs.containers }}
      platforms: ${{ steps.rhub-setup.outputs.platforms }}
    steps:
      # NO NEED TO CHECKOUT HERE
      - uses: r-hub/actions/setup@v1
        with:
          config: ${{ github.event.inputs.config }}
        id: rhub-setup
      - uses: r-lib/actions/setup-tinytex@v2
      - uses: r-lib/actions/setup-pandoc@v2

  all-platforms:
    needs: setup
    # Merge containers and platforms output for a unified matrix
    if: ${{ needs.setup.outputs.containers != '[]' || needs.setup.outputs.platforms != '[]' }}
    # Use ubuntu as default, override with matrix when available
    runs-on: ${{ matrix.config.os || 'ubuntu-latest' }}
    name: ${{ matrix.config.label }}
    strategy:
      fail-fast: false
      # Merge both containers and platforms to a single matrix
      matrix:
        config: ${{ fromJson(
          (
            needs.setup.outputs.containers != '[]'
              && needs.setup.outputs.platforms != '[]'
          )
          && join(',', needs.setup.outputs.containers, needs.setup.outputs.platforms)
          || (needs.setup.outputs.containers != '[]'
              && needs.setup.outputs.containers
            )
          || needs.setup.outputs.platforms
        ) }}

    # If container is set in matrix, use it, otherwise run natively
    container: ${{ matrix.config.container && fromJson('{"image":"' + matrix.config.container + '"}') || null }}

    steps:
      - uses: r-hub/actions/checkout@v1
      # Setup R (for non-container jobs)
      - name: Setup R
        if: ${{ !matrix.config.container }}
        uses: r-hub/actions/setup-r@v1
        with:
          job-config: ${{ matrix.config.job-config }}
          token: ${{ secrets.RHUB_TOKEN }}
          extra-packages: |
            any::rcmdcheck
            lixoftConnectors=?ignore
      # Platform info step (always)
      - uses: r-hub/actions/platform-info@v1
        with:
          token: ${{ secrets.RHUB_TOKEN }}
          job-config: ${{ matrix.config.job-config }}
          extra-packages: |
            any::rcmdcheck
            lixoftConnectors=?ignore
      # Setup dependencies (always)
      - uses: r-hub/actions/setup-deps@v1
        with:
          job-config: ${{ matrix.config.job-config }}
          token: ${{ secrets.RHUB_TOKEN }}
          extra-packages: |
            any::rcmdcheck
            lixoftConnectors=?ignore
      # TinyTeX and Pandoc (always, safe in container too)
      - uses: r-lib/actions/setup-tinytex@v2
      - uses: r-lib/actions/setup-pandoc@v2
      # Run R CMD check
      - uses: r-hub/actions/run-check@v1
        env:
          BUILD_ARGS: --compact-vignettes=both
        with:
          job-config: ${{ matrix.config.job-config }}
          token: ${{ secrets.RHUB_TOKEN }}
